# Setup environment for Docker
language: generic
services: docker
notifications:
  email: false

# Declare cache directory for docker image cache
cache:
  directories:
    - ~/docker

# Environment setup before test script
before_install:
  - git branch
  - git remote -v
  - ls ~/docker -lh
  - docker images
  - sudo chgrp -hR 1000 $CNG_HOST_PATH
  # Load cached docker images
  - if [[ -f $DOCKER_CACHE ]]; then gunzip -c $DOCKER_CACHE | docker load; fi
  # Build docker image
  #- docker build tools/docker -t $DOCKER_IMG
  - mkdir -p $(dirname $DOCKER_CACHE)
  #- mkdir -p ~/docker
  #- if [[ -f $DOCKER_CACHE ]]; then echo "exists."; cat $DOCKER_CACHE ; fi
  #- ls ~
  - ls ~/docker -lh
  - docker images
  #- echo "Test" > $DOCKER_CACHE
  #- docker pull $DOCKER_IMG
  # Cache all layers
  - docker save $DOCKER_IMG $(docker history -q $DOCKER_IMG) | gzip > $DOCKER_CACHE
  - ls ~/docker -lh
  - docker images
  #- ls ~/docker -lh
  # Build Cooja
  #- ant -q -f $CNG_HOST_PATH/tools/cooja/build.xml jar

# The test script for each build
script:
  #- docker run --privileged -v $CNG_HOST_PATH:/home/user/contiki-ng -ti $DOCKER_IMG bash --login -c "make -C tests/??-$TEST_NAME";
  # Check outcome of the test
  #- $CNG_HOST_PATH/tests/check-test.sh $CNG_HOST_PATH/tests/??-$TEST_NAME; exit $?;

# Environment variables
env:
  # Global environment variables, i.e., set for all builds
  global:
    - DOCKER_IMG=simonduq/contiki-ng:latest
    - DOCKER_CACHE=~/docker/cache2.tgz
    - CNG_HOST_PATH=`pwd`
  # Each line in the 'matrix' triggers a separate Travis build
  matrix:
    #- TEST_NAME='compile-base'
    #- TEST_NAME='compile-arm-ports-01'
    #- TEST_NAME='compile-arm-ports-02'
    #- TEST_NAME='rpl-lite'
    #- TEST_NAME='rpl-classic'
    #- TEST_NAME='tun-rpl-br'
    #- TEST_NAME='coap-lwm2m'
    #- TEST_NAME='simulation-base'
    #- TEST_NAME='ieee802154'
    #- TEST_NAME='compile-nxp-ports'
    #- TEST_NAME='doxygen'
    - TEST_NAME='compile-tools'
    #- TEST_NAME='native-runs'
    #- TEST_NAME='ipv6'
