# Setup environment for Docker
language: generic
services: docker
notifications:
  email: false

# Declare cache directory for docker image cache
cache:
  directories:
    - ~/docker

# Environment setup before test script
before_install:
  - sudo chgrp -hR 1000 $CNG_HOST_PATH
  # Load cached docker images
  #- if [[ -e $DOCKER_CACHE_FILE ]]; then gunzip -c $DOCKER_CACHE_FILE | docker load ; fi
  # Build docker image
  #- docker build tools/docker -t $DOCKER_IMG
  #- mkdir -p $(dirname $DOCKER_CACHE_FILE)
  - mkdir -p ~/docker
  - if [[ -f $DOCKER_CACHE_FILE ]]; then echo "exists."; cat $DOCKER_CACHE_FILE ; fi
  - ls
  - ls docker
  - echo "Test" > $DOCKER_CACHE_FILE
  #- docker pull $DOCKER_IMG
  # Cache all layers
  #- docker save $DOCKER_IMG | gzip > $DOCKER_CACHE_FILE
  # Build Cooja
  #- ant -q -f $CNG_HOST_PATH/tools/cooja/build.xml jar

# The test script for each build
script:
  #- docker run --privileged -v $CNG_HOST_PATH:/home/user/contiki-ng -ti $DOCKER_IMG bash --login -c "make -C tests/??-$TEST_NAME";
  # Check outcome of the test
  #- $CNG_HOST_PATH/tests/check-test.sh $CNG_HOST_PATH/tests/??-$TEST_NAME; exit $?;

# Environment variables
env:
  # Global environment variables, i.e., set for all builds
  global:
    - DOCKER_IMG='simonduq/contiki-ng:latest'
    - DOCKER_CACHE_FILE='~/docker/cache.tgz'
    - CNG_HOST_PATH=`pwd`
  # Each line in the 'matrix' triggers a separate Travis build
  matrix:
    #- TEST_NAME='compile-base'
    #- TEST_NAME='compile-arm-ports-01'
    #- TEST_NAME='compile-arm-ports-02'
    #- TEST_NAME='rpl-lite'
    #- TEST_NAME='rpl-classic'
    #- TEST_NAME='tun-rpl-br'
    #- TEST_NAME='coap-lwm2m'
    #- TEST_NAME='simulation-base'
    #- TEST_NAME='ieee802154'
    #- TEST_NAME='compile-nxp-ports'
    #- TEST_NAME='doxygen'
    - TEST_NAME='compile-tools'
    #- TEST_NAME='native-runs'
    #- TEST_NAME='ipv6'
