CONTIKI_PROJECT = test-sensors
CONTIKI_TARGET_SOURCEFILES += efr-cmds.c
all: $(CONTIKI_PROJECT)

MODULES += os/services/shell

PLATFORMS_ONLY = efr32tb

CONTIKI = ../../..
include $(CONTIKI)/Makefile.include
